language: cpp
dist: trusty
sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

cache: apt

notifications:
  slack: dgtal:FObxCZFoeQkkaRuktJD5uhnN

secure: "Ra00iyQ+5wm7G3XfaaI40aKgfcGTigfmEd+3/TY1hYcjYnJvNOG0dekolcMDSelE8SfqLcWYnK6+vtOCmyZuUWheUhA+83Tgq/bIH6dMzSvLkJdyq2D9me4sX6zx3ct90swP7Adj8EBHmv61pH5OBeEcmNWJNIZmNQs3+1awca4="

addons:
  apt:
   sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
   packages:
    - libhdf5-serial-dev
    - libboost-dev
    - libcairo2-dev
    - libboost-system-dev
    - libboost-program-options-dev
    - libgmp-dev
    - libgdcm2-dev
    - libgraphicsmagick++1-dev
    - libqglviewer-dev
    - libinsighttoolkit3-dev
    - libfftw3-dev
    - g++-5

############
# Main rules
############
script:
  - source .travis/before_global.sh

jobs:
 include:
   - stage: "DGtalTools"
     name: "Testing DGtalTools against this DGtal branch"
     script: /bin/true
      - source .travis/before_global.sh
      - source .travis/getAndCheckDGtalTools.sh
   - stage: "Deploy"
     name: "Building and deploying the documentation"
     script: /bin/true
