language: cpp
dist: trusty
sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx


cache: apt

notifications:
  slack: dgtal:FObxCZFoeQkkaRuktJD5uhnN

########
# matrix details:
#    - one build for the documentation on macosx (clang) and only for commits on
#      DGtal-team repo (no pull request). Encrypted var. required.
#    - No gcc on macos
#    - clang build of dgtaltools in linux only. In this case, some dependencies are considerd in DGtal (GMP, QGLViewer, CAIRO, HDF5, FFTW3)
#    - Otherwise, 2 os x 2 configs
#
########
env:
  - CONFIG="Debug,Magick,GMP,ITK,FFTW3"
  - CONFIG="Debug,Cairo,QGLviewer,HDF5,EIGEN"
  - CONFIG="Documentation"
  - CONFIG="DGtalTools"

secure: "Ra00iyQ+5wm7G3XfaaI40aKgfcGTigfmEd+3/TY1hYcjYnJvNOG0dekolcMDSelE8SfqLcWYnK6+vtOCmyZuUWheUhA+83Tgq/bIH6dMzSvLkJdyq2D9me4sX6zx3ct90swP7Adj8EBHmv61pH5OBeEcmNWJNIZmNQs3+1awca4="


matrix:
  fast_finish: true
  exclude:
    - os: osx
      env: CONFIG="Documentation"
    - compiler: gcc
      os: linux
      env: CONFIG="Documentation"
    - compiler: gcc
      env: CONFIG="DGtalTools"
    - os: osx
      env: CONFIG="DGtalTools"
    - os: osx
      compiler: gcc


addons:
  apt:
   sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
   packages:
    - libhdf5-serial-dev
    - libboost-dev
    - libcairo2-dev
    - doxygen
    - doxygen-latex
    - graphviz
    - libboost-system-dev
    - libboost-program-options-dev
    - libgmp-dev
    - libgdcm2-dev
    - libgraphicsmagick++1-dev
    - libqglviewer-dev
    - libinsighttoolkit3-dev
    - libfftw3-dev
    - g++-5

############
# Main rules
############

jobs:
 include:
   - stage: "Testing DGtal"
     name: "Unit Tests"
     script:
        - source .travis/before_global.sh
        - "$SRC_DIR/.travis/configure_build.sh"
        - if [ $BUILD_DGTAL == "true" ]; then "$SRC_DIR/.travis/build_dgtal.sh"; fi
        - if [ $BUILD_DEC == "true" ]; then "$SRC_DIR/.travis/build_dec.sh"; fi
        - if [ $BUILD_EXAMPLES == "true" ]; then "$SRC_DIR/.travis/build_examples.sh"; fi
        - if [ $BUILD_TESTS == "true" ]; then "$SRC_DIR/.travis/build_tests.sh"; fi
        - if [ $BUILD_TESTS == "true" ]; then "$SRC_DIR/.travis/check_tests.sh"; fi
        - if [ $BUILD_DGTAL == "true" ]; then "$SRC_DIR/.travis/build_all.sh"; fi
        - if [ $CONFIG == "DGtalTools" ]; then "$SRC_DIR/.travis/getAndCheckDGtalTools.sh" ; fi
        - if [ $BUILD_DOC == "true" ]; then "$SRC_DIR/.travis/build_doc.sh"; fi
        - if [ $BUILD_DOC == "true" ]; then "$SRC_DIR/.travis/checkDoxygenDocumentation.sh"; fi
   - stage: "Deploy"
     name: "Deploying Documentation"
     script: /bin/true

###########
## Building the documentation
###########
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $SECRET_GITHUB_TOKEN
    keep-history: true
    on:
        condition: $BUILD_DOC=="true"
    local-dir: documentation
    repo: DGtal-team/testingdgtal.github.io
    target-branch: master
 