language: cpp
dist: trusty
sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  fast_finish: true
  exclude:
    - os: osx
      compiler: gcc


cache: apt

notifications:
  slack: dgtal:FObxCZFoeQkkaRuktJD5uhnN

secure: "Ra00iyQ+5wm7G3XfaaI40aKgfcGTigfmEd+3/TY1hYcjYnJvNOG0dekolcMDSelE8SfqLcWYnK6+vtOCmyZuUWheUhA+83Tgq/bIH6dMzSvLkJdyq2D9me4sX6zx3ct90swP7Adj8EBHmv61pH5OBeEcmNWJNIZmNQs3+1awca4="

##Deps for linux builds
addons:
  apt:
   sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
   packages:
    - libhdf5-serial-dev
    - libboost-dev
    - libcairo2-dev
    - libboost-system-dev
    - libboost-program-options-dev
    - libgmp-dev
    - libgdcm2-dev
    - libgraphicsmagick++1-dev
    - libqglviewer-dev
    - libinsighttoolkit3-dev
    - libfftw3-dev
    - g++-5

############
# Main rules
############
script:
  - source .travis/before_global.sh
  - source .travis/build_all.sh
  - cd "$TRAVIS_BUILD_DIR"
  - echo "Checking, dir=$PWD"
  - source .travis/check_tests.sh

jobs:
 include:
   - stage: "DGtalTools"
     name: "Testing DGtalTools + DGtal"
     script:
       - source .travis/before_global.sh
       - source .travis/build_dgtal.sh
       - source .travis/getAndCheckDGtalTools.sh
   - stage: "Documentation"
     name: "Building and deploying the documentation"
     script:  #need doxygen first
       - source .travis/before_global.sh
       - source .travis/install_doxygen.sh
       - source .travis/build_dgtal.sh
       - source .travis/build_doc.sh
       - source .travis/checkDoxygenDocumentation.sh
